# vim:ff=unix ts=2 sw=2 ai expandtab
---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
      - id: check-added-large-files
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: check-symlinks
      - id: detect-private-key
      - id: trailing-whitespace
      - id: requirements-txt-fixer
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.20.0
    hooks:
      - id: yamllint
  - repo: https://github.com/amperser/proselint/
    rev: 0.10.2
    hooks:
      - id: proselint
        types: [plain-text]
        exclude: LICENSE
  - repo: https://github.com/ambv/black
    rev: 19.10b0
    hooks:
      - id: black
        exclude: &excluded_pythonscripts pythonrc.py|rabbitmqadmin
        args:
          - |
              --line-length=79
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.9
    hooks:
      - id: flake8
        exclude: *excluded_pythonscripts
        args:
          - |-
            --max-line-length=79
        additional_dependencies:
          - flake8-bugbear
  - repo: https://github.com/pre-commit/mirrors-pylint
    rev: v2.4.4
    hooks:
      - id: pylint
        exclude: *excluded_pythonscripts
        args:
          - |-
            --disable=R0801
  - repo: https://www.shore.co.il/git/docker-pre-commit
    rev: v0.3.0
    hooks:
      - id: hadolint
      - id: docker-compose
